# Generated by Django 4.2.2 on 2023-07-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_alter_wishlist_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
