# Generated by Django 4.2.2 on 2023-07-13 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_anonymoususer_alter_note_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wishlist_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
