# Generated by Django 4.2.2 on 2023-07-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_wishlist_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stockL',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='stockM',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='stockS',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='stockXL',
            field=models.IntegerField(default=0),
        ),
    ]
