# Generated by Django 4.2.2 on 2023-07-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_stockl_product_stockm_product_stocks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stockL',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stockM',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stockS',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stockXL',
        ),
        migrations.AddField(
            model_name='product',
            name='tailleXXL',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='tailleL',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='tailleM',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='tailleS',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='tailleXL',
            field=models.IntegerField(default=0),
        ),
    ]
