# Generated by Django 4.2.2 on 2023-07-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_product_taillel_remove_product_taillem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selected_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
