# Generated by Django 4.2.2 on 2023-07-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_selected_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='selected_size',
            field=models.CharField(default='S', max_length=10),
        ),
    ]
