# Generated by Django 4.2.2 on 2023-07-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_product_stock_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='selected_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wishlist_users',
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
