# Generated by Django 4.2.2 on 2023-07-15 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_selected_size_product_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
