# Generated by Django 4.2.2 on 2023-07-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.JSONField(default=dict),
        ),
    ]
