# Generated by Django 4.2.2 on 2023-07-17 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='wishlist_users',
        ),
    ]
