# Generated by Django 4.2.2 on 2023-07-17 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_remove_product_wishlist_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Achat',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
