# Generated by Django 4.2.2 on 2023-07-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='S', max_length=20),
        ),
    ]
