# Generated by Django 4.2.2 on 2023-07-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_remove_product_wishlist_users'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='produits_wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlists', to='product.product'),
        ),
    ]
