# Generated by Django 4.2.2 on 2023-07-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_produits_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='value',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Web', 'Web'), ('Member', 'Member')], max_length=50),
        ),
    ]
